import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AreaChart, Area, ResponsiveContainer, Tooltip, XAxis, YAxis} from 'recharts';
import {LayoutDashboard, ArrowLeftRight, Plus, Search, WalletCards, PieChart, Settings, Trash2, X, TrendingUp, TrendingDown, CircleDollarSign, Layers3, Menu, ChevronRight, RefreshCw, Wifi, Upload} from 'lucide-react';
import * as XLSX from 'xlsx';
import './styles.css';

const API=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'');
const money=(n)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n||0));
const pct=(n)=>`${Number(n||0)>=0?'+':''}${Number(n||0).toFixed(2)}%`;
const parseNumber=(value)=>Number(String(value??'').replace(/[₹,%]/g,'').replace(/,/g,'').trim())||0;
function parseDelimited(text){
 const delimiter=text.split(/\r?\n/)[0].includes('\t')?'\t':','; const rows=[]; let row=[],cell='',quoted=false;
 for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'&&quoted&&next==='"'){cell+='"';i++;continue}if(ch==='"'){quoted=!quoted;continue}if(ch===delimiter&&!quoted){row.push(cell);cell='';continue}if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';continue}cell+=ch;}
 if(cell||row.length){row.push(cell);if(row.some(v=>v.trim()))rows.push(row);} return rows;
}
function parseMutualFundRows(rows){
 if(rows.length<2)throw new Error('The file must contain a header row and at least one mutual fund.');
 const normalize=(value)=>String(value).toLowerCase().replace(/[.\-_/]/g,'').replace(/\s+/g,'');
 const headers=rows[0].map(normalize); const aliases={schemename:'schemeName',amc:'amc',category:'category',subcategory:'subCategory',foliono:'folioNo',source:'source',units:'units',investedvalue:'invested',currentvalue:'value',returns:'returns',xirr:'xirr'};
 const indexes={}; headers.forEach((header,index)=>{if(aliases[header])indexes[aliases[header]]=index;});
 const required=['schemeName','units','invested','value']; if(required.some(key=>indexes[key]===undefined))throw new Error('Required headers: Scheme Name, Units, Invested Value and Current Value.');
 return rows.slice(1).map(row=>Object.fromEntries(Object.entries(indexes).map(([key,index])=>[key,['units','invested','value','returns','xirr'].includes(key)?parseNumber(row[index]):String(row[index]||'').trim()]))).filter(row=>row.schemeName);
}
function parseStockRows(rows){
 if(rows.length<2)throw new Error('The file must contain a header row and at least one stock.');
 const normalize=(value)=>String(value).toLowerCase().replace(/[.\-_/&]/g,'').replace(/\s+/g,'');
 const headers=rows[0].map(normalize); const aliases={stockname:'symbol',isin:'isin',quantity:'qty',averagebuyprice:'avg',buyvalue:'invested',closingprice:'ltp',closingvalue:'value',unrealisedpl:'pnl',unrealizedpl:'pnl'};
 const indexes={}; headers.forEach((header,index)=>{if(aliases[header])indexes[aliases[header]]=index;});
 const required=['symbol','qty','invested','ltp','value']; if(required.some(key=>indexes[key]===undefined))throw new Error('Required headers: Stock Name, Quantity, Buy value, Closing price and Closing value.');
 return rows.slice(1).map(row=>Object.fromEntries(Object.entries(indexes).map(([key,index])=>[key,['qty','avg','invested','ltp','value','pnl'].includes(key)?parseNumber(row[index]):String(row[index]||'').trim()]))).filter(row=>row.symbol);
}
function parseImportRows(rows){
 const headers=rows[0].map(value=>String(value).toLowerCase());
 return headers.some(value=>value.includes('stock name')||value.includes('isin'))?{kind:'stocks',rows:parseStockRows(rows)}:{kind:'mutualFunds',rows:parseMutualFundRows(rows)};
}
function parseMutualFundFile(text){return parseMutualFundRows(parseDelimited(text));}
async function parseMutualFundUpload(file){
 if(file.name.toLowerCase().endsWith('.xlsx')){
  const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'});
  const sheetName=workbook.SheetNames[0];
  if(!sheetName)throw new Error('The Excel workbook has no worksheets.');
  return parseImportRows(XLSX.utils.sheet_to_json(workbook.Sheets[sheetName],{header:1,defval:''}));
 }
 return parseImportRows(parseDelimited(await file.text()));
}

function App(){
 const [tab,setTab]=useState('dashboard');
 const [data,setData]=useState({transactions:[],quotes:{},snapshots:[],holdings:[],totals:{invested:0,value:0,pnl:0,returnPct:0,realized:0,todayPnl:0},market:{open:false,label:'Market closed'}});
 const [modal,setModal]=useState(false); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [mobileOpen,setMobileOpen]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await fetch(`${API}?action=portfolio`);const next=await r.json();if(next.ok!==false)setData(next);}finally{setLoading(false)}};
 const refreshQuotes=async()=>{setRefreshing(true);try{const r=await fetch(`${API}?action=refreshQuotes`);const next=await r.json();if(next.ok){setData(d=>({...d,quotes:next.quotes,market:next.market}));await load();}}catch(e){console.error(e)}finally{setRefreshing(false)}};
 useEffect(()=>{load().then(()=>refreshQuotes());},[]);
 useEffect(()=>{const timer=setInterval(()=>{if(!document.hidden)refreshQuotes();},60000);return()=>clearInterval(timer);},[]);
 const holdings=data.holdings||[]; const totals=data.totals||{invested:0,value:0,pnl:0,returnPct:0,realized:0,todayPnl:0};
 const nav=[['dashboard','Dashboard',LayoutDashboard],['holdings','Holdings',WalletCards],['transactions','Transactions',ArrowLeftRight],['analytics','Analytics',PieChart],['settings','Settings',Settings]];
 return <div className="app">
  <aside className={`sidebar ${mobileOpen?'open':''}`}><div className="brand"><div className="brandmark">L</div><div><b>Ledgerly</b><span>Portfolio</span></div></div>{nav.map(([id,label,Icon])=><button key={id} className={`nav ${tab===id?'active':''}`} onClick={()=>{setTab(id);setMobileOpen(false)}}><Icon size={19}/>{label}</button>)}<div className="side-bottom"><div className="secure"><CircleDollarSign size={18}/><div><b>Private by design</b><span>Data stored in Google Sheets</span></div></div></div></aside>
  {mobileOpen&&<div className="scrim" onClick={()=>setMobileOpen(false)}/>} 
    <main className="main"><header><button className="mobile-menu" onClick={()=>setMobileOpen(true)}><Menu/></button><div><span className="eyebrow">PERSONAL WEALTH</span><h1>{tab==='dashboard'?'Portfolio overview':tab[0].toUpperCase()+tab.slice(1)}</h1></div><div className="header-actions"><MarketBadge market={data.market}/><button className="icon-btn" title="Refresh prices" onClick={refreshQuotes} disabled={refreshing}><RefreshCw size={18} className={refreshing?'spin':''}/></button><label className="secondary import-button" title="Import stock or mutual-fund Excel, CSV or TSV"><Upload size={17}/><span>Import data</span><input type="file" accept=".xlsx,.csv,.tsv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv,text/tab-separated-values" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{const imported=await parseMutualFundUpload(file);const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'importData',kind:imported.kind,rows:imported.rows})});const next=await r.json();if(!r.ok||next.ok===false)throw new Error(next.error||'Import failed');await load();alert(`Imported ${next.count} ${imported.kind==='stocks'?'stock':'mutual fund'} rows.`);}catch(error){alert(error.message||'Could not import data.')}e.target.value='';}}/></label><button className="primary" onClick={()=>setModal(true)}><Plus size={18}/> Add transaction</button></div></header>
   {tab==='dashboard'&&<Dashboard totals={totals} holdings={holdings} snapshots={data.snapshots||[]} market={data.market} quotes={data.quotes}/>} {tab==='holdings'&&<Holdings holdings={holdings}/>} {tab==='transactions'&&<Transactions txs={data.transactions||[]} onRefresh={load}/>} {tab==='analytics'&&<Analytics holdings={holdings} totals={totals}/>} {tab==='settings'&&<SettingsPage onRefresh={load}/>} 
  </main>
  {modal&&<TransactionModal onClose={()=>setModal(false)} onSaved={()=>{setModal(false);load();refreshQuotes()}}/>}
 </div>
}

function MarketBadge({market}){const open=!!market?.open;return <div className={`market-badge ${open?'open':'closed'}`} title={`${market?.reason||''}${market?.time?' • '+market.time+' IST':''}`}><span className="market-dot"/>{open?'Market open':'Market closed'}</div>}

function Dashboard({totals,holdings,snapshots,market,quotes}){return <div className="content">
 <section className="hero-card"><div><span className="muted">Current portfolio value</span><div className="hero-value">{money(totals.value)}</div><div className={totals.pnl>=0?'gain hero-pnl':'loss hero-pnl'}>{totals.pnl>=0?<TrendingUp size={18}/>:<TrendingDown size={18}/>} {money(totals.pnl)} <span>({pct(totals.returnPct)})</span></div><div className="price-meta">{market?.open?'Prices updating while the NSE session is open':'Showing latest available prices'} · {lastQuoteTime(quotes)||'No quote yet'}</div></div><div className="hero-stat"><span>Invested</span><b>{money(totals.invested)}</b><small>{holdings.length} positions</small></div></section>
 <div className="metric-grid"><Metric title="Today's P&L" value={money(totals.todayPnl||0)} note="vs previous close" positive={(totals.todayPnl||0)>=0}/><Metric title="Unrealized P&L" value={money(totals.pnl)} note={pct(totals.returnPct)} positive={totals.pnl>=0}/><Metric title="Realized P&L" value={money(totals.realized)} note="From closed lots" positive={totals.realized>=0}/><Metric title="Largest position" value={holdings[0]?.symbol||'—'} note={holdings[0]?money(holdings[0].value):'No holdings yet'}/></div>
 <div className="section-head"><div><h2>Portfolio performance</h2><p>Value history from saved daily snapshots.</p></div><span className="pill">Live valuation</span></div>
 <div className="chart-card">{snapshots.length?<ResponsiveContainer width="100%" height={300}><AreaChart data={snapshots}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#6d5ce7" stopOpacity={.24}/><stop offset="95%" stopColor="#6d5ce7" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="date" tickLine={false} axisLine={false}/><YAxis tickFormatter={v=>`₹${Math.round(v/1000)}k`} tickLine={false} axisLine={false}/><Tooltip formatter={v=>money(v)}/><Area type="monotone" dataKey="value" stroke="#6d5ce7" fill="url(#fill)" strokeWidth={3}/></AreaChart></ResponsiveContainer>:<Empty icon={<TrendingUp size={25}/>} title="Your performance chart starts here" text="Add transactions to build your portfolio history. No sample data is included."/>}</div>
 <div className="section-head"><div><h2>Holdings</h2><p>Live price, weighted cost and unrealized return.</p></div><span className="linkish">{market?.open?'Prices refreshing every minute':'Latest available prices'} <ChevronRight size={15}/></span></div>
 <Holdings holdings={holdings.slice(0,5)} compact/>
 <div className="feed-note"><Wifi size={15}/><span><b>Price feed:</b> GoogleFinance / NSE. Quotes can be delayed by up to 20 minutes; this dashboard is for portfolio tracking, not order execution.</span></div>
 </div>}
function lastQuoteTime(quotes){const vals=Object.values(quotes||{}).map(q=>q.updatedAt).filter(Boolean);return vals.length?vals.sort().at(-1):''}
function Metric({title,value,note,positive,muted}){return <div className="metric"><span>{title}</span><b className={positive===true?'gain':positive===false?'loss':''}>{value}</b><small className={muted?'muted':''}>{note}</small></div>}
function Holdings({holdings,compact}){return <div className="holdings-card">{holdings.length===0?<Empty title="No holdings yet" text="Add your first BUY transaction to create a lot." icon={<Layers3 size={25}/>}/>:<div className="holdings-list">{holdings.map(h=><div className="holding-row" key={`${h.symbol}-${h.mutualFund?.folioNo||h.assetType}`}><div className="asset"><div className="asset-icon">{h.symbol.slice(0,1)}</div><div><b>{h.displayName||h.symbol}</b><span>{h.qty} units · avg {money(h.avg)} · LTP {money(h.ltp)}</span></div></div><div className="holding-price"><b>{money(h.value)}</b><span className={h.pnl>=0?'gain':'loss'}>{money(h.pnl)} · {pct(h.returnPct)}</span>{h.previousClose>0&&<small className={h.dayPnl>=0?'gain':'loss'}>Today {money(h.dayPnl||0)}</small>}</div><div className="mini-bar"><span style={{width:`${Math.min(100,Math.max(2,Math.abs(h.returnPct)))}%`}}/></div></div>)}</div>}</div>}
function Transactions({txs,onRefresh}){const [q,setQ]=useState('');const filtered=txs.filter(t=>`${t.symbol} ${t.note||''}`.toLowerCase().includes(q.toLowerCase()));return <div className="content"><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search symbol or note" value={q} onChange={e=>setQ(e.target.value)}/></div><span className="muted">{filtered.length} transactions</span></div><div className="table-card">{filtered.length===0?<Empty title="No transactions" text="Your transaction ledger is empty. Add a BUY or SELL to begin." icon={<ArrowLeftRight size={25}/>}/>:<table><thead><tr><th>Date</th><th>Symbol</th><th>Type</th><th>Qty</th><th>Price</th><th>Charges</th><th>Total</th><th></th></tr></thead><tbody>{filtered.map(t=><tr key={t.id}><td>{t.date}</td><td><b>{t.symbol}</b></td><td><span className={`type ${t.type.toLowerCase()}`}>{t.type}</span></td><td>{t.quantity}</td><td>{money(t.price)}</td><td>{money(t.charges)}</td><td>{money(t.total)}</td><td><button className="danger-icon" onClick={async()=>{await fetch(`${API}?action=deleteTransaction&id=${encodeURIComponent(t.id)}`);onRefresh()}}><Trash2 size={16}/></button></td></tr>)}</tbody></table>}</div></div>}
function Analytics({holdings,totals}){return <div className="content"><div className="analytics-grid"><div className="dark-panel"><span className="muted">Portfolio P&L</span><strong>{money(totals.pnl)}</strong><div className={totals.pnl>=0?'gain':'loss'}>{pct(totals.returnPct)} on invested capital</div></div><div className="insight-card"><span className="muted">Position count</span><strong>{holdings.length}</strong><p>Each purchase is tracked as an independent lot, so repeated buys retain their original price and date.</p></div></div><div className="table-card"><div className="card-title"><div><h2>Lot-level exposure</h2><p>Every position is derived from its individual purchase lots.</p></div></div>{holdings.length?<table><thead><tr><th>Symbol</th><th>Lots</th><th>Quantity</th><th>Avg cost</th><th>Current value</th><th>P&L</th></tr></thead><tbody>{holdings.map(h=><tr key={h.symbol}><td><b>{h.symbol}</b></td><td>{h.lots.length}</td><td>{h.qty}</td><td>{money(h.avg)}</td><td>{money(h.value)}</td><td className={h.pnl>=0?'gain':'loss'}>{money(h.pnl)}</td></tr>)}</tbody></table>:<Empty title="Analytics will appear here" text="Add transactions to calculate portfolio analytics."/>}</div></div>}
function SettingsPage({onRefresh}){return <div className="content"><div className="settings-card"><div><h2>Portfolio settings</h2><p>Transactions remain manual, while held NSE stocks are valued using the live-price refresh.</p></div><div className="setting-row"><div><b>Accounting method</b><span>FIFO is used for lot matching on sells.</span></div><span className="pill">FIFO</span></div><div className="setting-row"><div><b>Market feed</b><span>NSE stock quotes refresh automatically. GoogleFinance quotes may be delayed by up to 20 minutes.</span></div><span className="pill">GoogleFinance</span></div><div className="setting-row"><div><b>Data storage</b><span>Google Sheets via Apps Script. No browser localStorage is used as the source of truth.</span></div><span className="pill">Sheets</span></div></div></div>}
function TransactionModal({onClose,onSaved}){const [form,setForm]=useState({type:'BUY',assetType:'STOCK',symbol:'',date:new Date().toISOString().slice(0,10),quantity:'',price:'',charges:'',note:''});const [saving,setSaving]=useState(false);const update=(k,v)=>setForm(f=>({...f,[k]:v}));const submit=async e=>{e.preventDefault();setSaving(true);const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'transaction',...form})});setSaving(false);if(r.ok)onSaved();else alert((await r.json()).error||'Could not save transaction')};return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><span className="eyebrow">LEDGER ENTRY</span><h2>Add transaction</h2></div><button className="icon-btn" onClick={onClose}><X/></button></div><form onSubmit={submit}><div className="seg"><button type="button" className={form.type==='BUY'?'on':''} onClick={()=>update('type','BUY')}>Buy</button><button type="button" className={form.type==='SELL'?'on':''} onClick={()=>update('type','SELL')}>Sell</button></div><div className="form-grid"><label>Asset type<select value={form.assetType} onChange={e=>update('assetType',e.target.value)}><option value="STOCK">Stock</option><option value="MF">Mutual fund</option></select></label><label>Symbol<input required placeholder="e.g. RELIANCE" value={form.symbol} onChange={e=>update('symbol',e.target.value.toUpperCase())}/></label><label>Date<input required type="date" value={form.date} onChange={e=>update('date',e.target.value)}/></label><label>Quantity<input required min="0.000001" step="any" type="number" placeholder="0" value={form.quantity} onChange={e=>update('quantity',e.target.value)}/></label><label>Traded price<input required min="0" step="any" type="number" placeholder="₹0" value={form.price} onChange={e=>update('price',e.target.value)}/></label><label>Brokerage + charges<input min="0" step="any" type="number" placeholder="₹0" value={form.charges} onChange={e=>update('charges',e.target.value)}/></label><label>Note<input placeholder="Optional" value={form.note} onChange={e=>update('note',e.target.value)}/></label></div><div className="calc"><span>Total consideration</span><b>{money(Number(form.quantity||0)*Number(form.price||0)+Number(form.charges||0))}</b></div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save transaction'}</button></div></form></div></div>}
function Empty({icon,title,text}){return <div className="empty">{icon&&<div className="empty-icon">{icon}</div>}<h3>{title}</h3><p>{text}</p></div>}
createRoot(document.getElementById('root')).render(<App/>);
